patient/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^seizureNow/$', views.seizureNow, name='seizureNow'),
    url(r'^monitor/$', views.monitor, name='monitor'),
    url(r'^monitor/statistics$', views.monitorStatistics, name='monitorStatistics'),
    url(r'^monitor/statistics/seizureDistribution.png$', views.seizureDistribution, name='seizureDistribution'),
    url(r'^monitor/statistics/seizureFrequency.png$', views.seizureFrequency, name='seizureFrequency'),
    url(r'^monitor/statistics/seizureFrequency.png/(?P<week>[0-9]{4}-[0-9]{2})/$',
        views.seizureFrequency,
        name='seizureFrequency'),
    url(r'^monitor/statistics/dailySeizureDistributionComparison.png$',
        views.dailySeizureDistributionComparison,
        name='dailySeizureDistributionComparison'),
    url(r'^monitor/weeklyReports/$',
        views.monitorWeeklyReports,
        name='monitorWeeklyReports'),
    url(r'^monitor/weeklyReports/(?P<week>[0-9]{4}-[0-9]{2})/$',
        views.monitorWeeklyReports,
        name='monitorWeeklyReports'),

    url(r'^camera$', views.camera, name='camera'),

    url(r'^sleepRythm/register/$', views.sleepRegister, name='sleepRegister'),
]

raspilepsy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('patient.urls')),
    url(r'^admin/', admin.site.urls),
]

patient/models.py
from __future__ import unicode_literals

from django.db import models

import datetime, pytz
from os import remove
# Create your models here.

class SeizureManager(models.Manager):
    def getDaysWithSeizures(self):

        pytz.timezone("Europe/Berlin")

        oldest = datetime.datetime.strptime(
                    datetime.datetime.strftime(
                        self.getOldestSeizure().time,
                        "%Y-%m-%d"),
                    "%Y-%m-%d")

        base = datetime.datetime.strptime(
                    datetime.datetime.strftime(
                        pytz.utc.localize(
                            datetime.datetime.today()),
                        "%Y-%m-%d"),
                     "%Y-%m-%d")
        timeRange = base-oldest
        dateRange = [base - datetime.timedelta(days=x) for x in reversed(range(0, timeRange.days))]
        return dateRange

    def getSeizuresPerNight(self, days=None):
        from datetime import timedelta
        if not days:
            days = self.getDaysWithSeizures()

        seizures = []

        for day in days:
            startTime = day - timedelta(hours=10)
            endTime = day + timedelta(hours=13, minutes=59)

            seizures.append(self.filter(time__range=(startTime, endTime)))

        return seizures

    def getOldestSeizure(self):
        """
        Returns the oldest seizure that is stored in the database
        """
        return self.all().order_by('time')[0]
    
    def getSeizureWeeks(self):
        """
        A datetime object is returned, hence the the list is unique. The latest
        week is the first one in the list.
        """
        return reversed(
                sorted(
                    list(
                        set(
                            [
                                "%i-%i" %(
                                    int(dateI.isocalendar()[0]),
                                    int(dateI.isocalendar()[1])
                                    )
                                for dateI in self.getDaysWithSeizures()]
                            )
                        )
                    )
                )

class Seizure(models.Model):

    time = models.DateTimeField('seizure time', auto_now_add=True)
    duration = models.IntegerField('duration in seconds')
    description = models.TextField(max_length=5000)
    objects = SeizureManager()

    def __str__(self):
        return "%is: %s" %(self.duration, self.description)


class PossibleSeizureFootageManager(models.Manager):

    def clean(self):
        """
        Removes false positives from the database, which have been marked as to
        be deleted previously. This method solely does the cleaning up and *not*
        the selection. If the footage file is still present, it is removed as
        well.
        """
        for fPI in self.getFalsePositives():
            try:
                remove(fPI.footage)
            except:
                pass
            fPI.delete()


    def getFalsePositives(self):
        """
        Returns a list of `PossibleSeizureFootage` instances that have already
        been marked as `toBeDeleted` and can be savely be deleted.
        """
        return self.all().order_by('-id').filter(toBeDeleted=True)

    def update(self):
        for sI in self.all():
            sI.duration = int((sI.endTime - sI.startTime).total_seconds())
            sI.save()


class PossibleSeizureFootage(models.Model):
    """
    Points to a single video footage file and serves the purpose of
    encapsulating e.g. video footage of multiple sources for a single seizure
    and correlating it to a seizure. It has hence a one-to-many relation to
    `Seizure`.
    """

    startTime = models.DateTimeField('start time', auto_now_add=False)
    endTime = models.DateTimeField('end time', auto_now_add=False)
    footage = models.CharField(max_length=200)
    hasManualTrigger = models.BooleanField()
    duration = models.IntegerField(default=-1)
    toBeDeleted = models.BooleanField(default=False)

    seizure = models.ForeignKey(
                    Seizure,
                    default=-1,
                    on_delete=models.CASCADE
                )

    objects = PossibleSeizureFootageManager()

    def __str__(self):
        return "%s (%i s) %r %r" %(
                self.footage,
                self.duration,
                self.hasManualTrigger,
                self.toBeDeleted
                )

    def save(self, *args, **kwargs):
        """
        Overloads the base-class save method, since the `hasManualTrigger` can
        be changed from other sources in the database and needs to be read. This
        change is accepted. Any other changes to data are *not accepted* and are
        hence ignored.
        """
        if self.pk is not None:
            orig = PossibleSeizureFootage.objects.get(pk=self.pk)
            self.hasManualTrigger = (orig.hasManualTrigger or self.hasManualTrigger)
            try:
                if orig.seizure.id > self.seizure.id:
                    self.seizure = orig.seizure
            except:
                pass
        super(PossibleSeizureFootage, self).save(*args, **kwargs)

    def stop(self, args):
        pytz.timezone("Europe/Berlin")
        self.endTime = pytz.utc.localize(datetime.datetime.now())
        self.duration = int((self.endTime - self.startTime).total_seconds())
        self.save()

        if self.duration < args["min_length"]:
            # The file can be remove immideatly. The database entry cannot be
            # removed right away, though. Since we are in `self`, we cannot
            # delete `self`. In order to work around that, we mark this data set
            # as `toBeDeleted` in the database and handle the delete process in
            # the manager.
            try:
                remove(self.footage)
            except:
                pass
            self.toBeDeleted = True
            self.save()

    def start(self):

        pytz.timezone("Europe/Berlin")
        self.hasManualTrigger = False
        self.startTime = pytz.utc.localize(datetime.datetime.now())
        self.endTime = pytz.utc.localize(datetime.datetime.now())
        self.save()

class Patient(models.Model):
    """
    Stores data of a patient. This is *unencrypted* for now, but the data is not
    sensitive. It is solely personal information.
    """
    firstname = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    weight = models.FloatField()
    height = models.FloatField()
    language = models.CharField(max_length=2, default='de')

    def __str__(self):
        return "%s, %s" %(self.surname, self.firstname)

class PatientMotion(models.Model):
    """
    Stores the motion of a patient in the database, so that it can be updated
    from various sources. Doing this simplifies various computations of time
    calculations as well and encapulates time and motion data.
    """

    lastMotionTime = models.DateTimeField('lastMotionTime', auto_now_add=False)
    isInMotionSince = models.DateTimeField('isInMotionSince', auto_now_add=False)
    isInMotion = models.BooleanField(default=False)

    patient = models.ForeignKey(
                    Patient,
                    default=-1,
                    on_delete=models.CASCADE
                )

    def __str__(self):
        return "%s, %s" %(self.patient.surname, self.patient.firstname)

    def moves(self):
        """
        This method needs to be called if motion of a patient is detected by any
        means.
        """
        pytz.timezone("Europe/Berlin")
        self.lastMotionTime = pytz.utc.localize(datetime.datetime.now())

        if not self.isInMotion:
            self.isInMotionSince = pytz.utc.localize(datetime.datetime.now())
            self.isInMotion = True

        self.save()

    def freezes(self):
        """
        This method needs to be called if the patient stops moving.
        """
        self.isInMotion = False
        self.save()

class SleepManager(models.Manager):

    def sleeps(self):
        try:
            out = self.all().order_by('-startTime').filter(isSleeping=True)[0]
            if out:
                return True
            else:
                return False
        except IndexError:
            return False


class Sleep(models.Model):

    startTime = models.DateTimeField('startTime', auto_now_add=False)
    endTime = models.DateTimeField('endTime', auto_now_add=False)
    isSleeping = models.BooleanField(default=False)

    patient = models.ForeignKey(
                    Patient,
                    default=-1,
                    on_delete=models.CASCADE
                )

    objects = SleepManager()

    def start(self):
        pytz.timezone("Europe/Berlin")
        self.startTime = pytz.utc.localize(datetime.datetime.now())
        self.endTime = pytz.utc.localize(datetime.datetime.now())
        self.isSleeping = True
        self.save()

    def stop(self):
        pytz.timezone("Europe/Berlin")
        self.endTime = pytz.utc.localize(datetime.datetime.now())
        self.isSleeping = False
        self.save()

patient/forms.py
from django import forms

class QuickAddSeizure(forms.Form):

    duration = forms.CharField(label='Seizure Duration in seconds', max_length=4)
    description = forms.CharField(label='Description', widget=forms.Textarea)

patient/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
{% load staticfiles %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>{% block head_title %}Raspilepsy{% endblock %}</title>

        <script type="text/javascript" async src="{% static "MathJax/MathJax.js"%}?config=TeX-MML-AM_CHTML"></script>

        <!-- Bootstrap -->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">-->


        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="#"><img src="{% static "logo.png" %}"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">{% trans "Dashboard" %} <span class="sr-only">(current)</span></a></li>

                    <li class="dropdown">
                        <a href="/monitor/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {% trans "Monitoring" %} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/monitor/">{% trans "Monitor" %}</a></li>
                            <li><a href="/monitor/statistics">{% trans "Statistics" %}</a></li>
                            <li><a href="/monitor/weeklyReports">{% trans "Weekly Reports" %}</a></li>
                        </ul>
                    </li>
                    <li><a href="#">{% trans "Medication" %}</a></li>

                    <li class="dropdown">
                        <a href="/sleepRythm/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {% trans "Sleep Rythm" %} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/sleepRythm/">{% trans "Sleep Rythm" %}</a></li>
                            <li><a href="/monitor/statistics">{% trans "Statistics" %}</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="label label-danger">{% trans "Camera offline" %}</span></a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{% block title %}{% trans "Dashboard" %}{% endblock %}</h1>
            </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!--<script src="js/bootstrap.min.js"></script>-->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

patient/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {% trans "Dashboard" %} {% endblock %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class=panel-heading>
                    <h3 class=panel-title>{% trans "Quick Add Seizure" %}</h3>
                </div>
                <div class=panel-body>
                    {% blocktrans %}

                    Please press this button, whenever you have a seizure.

                    {% endblocktrans %}

                    <form action="/seizureNow/" method="post">

                        {% csrf_token %}
                        {{ form_markSeizure }}
                        <center>
                            <button name="action" class="btn btn-danger btn-lg" value="seizureNow">
                                <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>{% trans "Seizure Now" %}
                            </button>
                        </center>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class=panel-heading>
                    <h3 class=panel-title>{% trans "Sleep Rythm" %}</h3>
                </div>
                <div class=panel-body>

                    <form action="/sleepRythm/register/" method="post">
                        {% blocktrans %}
                        Use this to register register your sleep rythm and
                        gather more data. 
                        {% endblocktrans %}</br>
                        {% csrf_token %}
                        {{ form_sleepRegister }}
                        <center>
                            <div class="btn-group btn-group-justified" role="group">
                                <div class="btn-group" role="group">
                                    {% if sleeping == True %}
                                        <button name="action" class="btn btn-default btn-lg btn-disabled" value="sleep" disabled>
                                    {% else %}
                                        <button name="action" class="btn btn-default btn-lg" value="sleep">
                                    {% endif %}
                                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>{% trans "Sleep" %}
                                    </button>
                                </div>
                                <div class="btn-group" role="group">
                                    {% if sleeping == False %}
                                        <button name="action" class="btn btn-default btn-lg btn-disabled" value="wakeUp" disabled>
                                    {% else %}
                                        <button name="action" class="btn btn-default btn-lg" value="wakeUp">
                                    {% endif %}
                                        <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>{% trans "Wake-Up" %}
                                    </button>

                                </div>
                            </div>
                        </center>
                    </form>

                </div>
            </div>
        </div>

        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class=panel-heading>
                    <h3 class=panel-title>{% trans "Video Capture" %}</h3>
                </div>
                <div class=panel-body>
                      <form action="/camera" method="post">
                        {% csrf_token %}
                        {{ form_startStopCamera }}

                        {% blocktrans %}
                        Control the video capture via this tile-interface. The
                        IR light is controled automatically.
                        {% endblocktrans %}

                        <center>
                            <div class="btn-group btn-group-justified" role="group">
                                <div class="btn-group" role="group">
                                    <button name="action" class="btn btn-default btn-lg" value="cameraStart">
                                        <span class="glyphicon glyphicon-play" aria-hidden="true"></span>{% trans "Start" %}
                                    </button>
                                </div>
                                <div class="btn-group" role="group">
                                    <button name="action" class="btn btn-default btn-lg" value="cameraStop">
                                        <span class="glyphicon glyphicon-stop" aria-hidden="true"></span>{% trans "Stop" %}
                                    </button>
                                </div>
                            </div>
                        </center>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">

            <div class="panel panel-primary">
                <div class=panel-heading>
                    <h3 class=panel-title>{% trans "Add Seizure" %}</h3>
                </div>
                <div class=panel-body>

                    <form action="/" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-default btn-lg" value="Submit">
                            <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>{% trans "Seizure Now" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-4">

            <div class="panel panel-info">
                <div class=panel-heading>
                    <h3 class=panel-title>{% trans "Weekly Reports" %}</h3>
                </div>
                <div class=panel-body>

                    <div style="margin-bottom: 2em">
                        {% blocktrans %}
                        Select a week to obtain a weekly report for that week. This
                        report can then be sent to your doctor in charge, or put
                        your own documents.
                        {% endblocktrans %}
                    </div>


                    <div class="input-group">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% trans "Select Week" %} <span class="caret"> </span>
                            </button>
                            <ul class="dropdown-menu">
                            {% for x in seizureWeeks %}
                                <li><a href="/monitor/weeklyReports/{{ x }}/">KW {{ x }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>{% trans "Recent Seizures" %}</h2>
        <div class="panel panel-default">
        <!-- Default panel contents -->
            <div class="panel-heading">{% trans "Recent Seizures" %}</div>

                <!-- Table -->
                <table class="table">
                    <tr>
                        <th>#</th>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Duration" %} [s]</th>
                        <th>{% trans "Description" %}</th>
                        <th></th>
                    </tr>

                    {% for seizure in seizures|slice:":10" reversed %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ seizure.time|date:"d-m-Y H:i:s" }}</td>
                        <td>{{ seizure.duration }}</td>
                        <td>{{ seizure.description|truncatewords:20 }}</td>
                        <td>
                            <button type="button" class="btn btn-default" aria-label="Edit">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

patient/templates/monitor.html
{% extends 'base.html' %}
{% block title %}Monitoring{% endblock %}

{% block content %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Last Night</div>

  <!-- Table -->
  <table class="table">
      <tr>
          <th>#</th>
          <th>Date</th>
          <th>Duration [s]</th>
          <th>Description</th>
          <th>Footage</th>
          <th></th>
      </tr>
    {% for seizure in seizures %}
      <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ seizure.time|date:"d-m-Y H:i:s" }}</td>
          <td>{{ seizure.duration }}</td>
          <td>{{ seizure.description|truncatewords:20 }}</td>
          <td>
              {{ seizure.possibleseizurefootage_set.all|length }}
          </td>
          <td>
            <button type="button" class="btn btn-default" aria-label="Edit">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>
          </td>
      </tr>
    {% endfor %}
  </table>
</div>

{% endblock %}

patient/templates/monitorStatistics.html
{% extends 'base.html' %}
{% block title %}Monitoring Statistics{% endblock %}

{% block content %}

{% load staticfiles %}

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Seizure Duration over Time</div>
                <div class="panel-body">
                    <img src="/monitor/statistics/seizureDistribution.png">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Seizure Frequency per Night (between 14:00h and 13:59h)</div>
                <div class="panel-body">
                    <img src="/monitor/statistics/seizureFrequency.png"></br>

                    {% if days|length > 0 %}
                      <!-- Table -->
                      <table class="table">
                          <tr>
                              <th>Day</th>
                              <th>`\bar{d}`</th>
                              <th>`\max{d}`</th>
                              <th>`\min{d}` {{ blubb }}</th>
                          </tr>
                          
                        {% for dayI in days %}
                          <tr>
                              <td>{{ dayI.time|date:"d-m-Y" }}</td>
                              <td>{{ durationMean.forloop.counter0 }}</td>
                              <td></td>
                              <td></td>
                          </tr>
                        {% endfor %}
                      </table>

                    {% endif %}
                </div>
                <div class="panel-footer">
                    The length `l` of the error bar is normalised by the maximal
                    seizure duration `d_\text{max}` and suffices: `l \in [0;
                    1]`. The intensity is not accounted for in this diagram,
                    since this is a <em>subjective</em> measure, yet. As soon as
                    sound is recorded, it can be based on that. An other
                    thinkable option is to use the live video analysis and
                    determine the maximum frame-in-motion as a function over
                    time.
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Seizure Distribution Comparison</div>
                <div class="panel-body">
                    <img src="/monitor/statistics/dailySeizureDistributionComparison.png">
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}